"""Builds src/jobs.js from a Tapi CSV export.
Usage: python3 scripts/build_jobs.py path/to/jobs.csv
Run this when you want a fresh job list, then commit and push."""
import csv, datetime as dt, json, sys

QUOTE_NOTES = {  # suggested prices for jobs awaiting a quote (edit as needed)
 'TAPI-03135': '$390 ($190 if done with TAPI-03034). We asked for photos.',
 'TAPI-03034': '$1,130. Same address as the lawns job.',
 'TAPI-03099': 'Free re-inspection (came back after our repair); $220 if a new fault.',
 'TAPI-02973': '$330 (about $180 on a regular run).',
 'TAPI-03096': '$340 bathroom only / $750 whole house. We asked which areas.',
 'TAPI-03061': '$170. All 3 Torquay jobs together about $1,200.',
 'TAPI-03060': '$360. Needs an electrician; we asked for the fan model.',
 'TAPI-03059': '$670.',
 'TAPI-03003': '$565. Use a local trade or combine with TAPI-02386.',
 'TAPI-02603': '$1,100 + $140/month. From July - check it is still wanted.',
 'TAPI-01638': '$170. From Feb - still waiting on photos.',
 'TAPI-02044': '$950-1,050. Other quote is $1.1k.',
 'TAPI-02056': '$550. Local QLD trade.',
 'TAPI-00856': '$180. Local QLD trade.',
 'TAPI-02178': '$115. Can the tenant replace it?',
}

def main(path):
    rows = list(csv.DictReader(open(path, encoding='utf-8-sig')))
    dates = []
    for x in rows:
        d, m, y = map(int, x['last_updated'].split('/'))
        x['_date'] = dt.date(y, m, d); dates.append(x['_date'])
    as_of = max(dates)
    out = []
    for x in rows:
        age = (as_of - x['_date']).days
        s = x['status']
        if x['urgent'] == 'Urgent': sec = 'urgent'
        elif s == 'Awaiting confirmation': sec = 'confirm'
        elif s == 'Scheduling job': sec = 'book'
        elif s == 'Awaiting invoice': sec = 'invoice'
        elif s == 'Awaiting quote': sec = 'quote'
        elif s == 'Awaiting approval' and age > 90: sec = 'oldquote'
        else: continue
        desc = ' '.join(x['description'].split())
        out.append({
            'id': x['job_number'], 'section': sec, 'title': x['title'].strip(),
            'address': x['full_address'].strip(), 'state': 'QLD' if 'QLD' in x['company'] else 'VIC',
            'pm': x['agent_name'], 'days': age, 'tapiStatus': s,
            'desc': desc[:400] + ('...' if len(desc) > 400 else ''),
            'tip': QUOTE_NOTES.get(x['job_number'], ''), 'url': x['url'],
        })
    order = ['urgent', 'confirm', 'book', 'invoice', 'quote', 'oldquote']
    out.sort(key=lambda j: (order.index(j['section']), -j['days']))
    with open('src/jobs.js', 'w') as f:
        f.write('// Generated by scripts/build_jobs.py - do not edit by hand\n')
        f.write(f'export const AS_OF = "{as_of.isoformat()}";\n')
        f.write('export const JOBS = ' + json.dumps(out, indent=1, ensure_ascii=False) + ';\n')
    print(len(out), 'jobs, as of', as_of)

if __name__ == '__main__':
    main(sys.argv[1])
